/**
 * entity.schema.ts
 *
 * Single source of truth for the entity creation data model.
 * Covers: Angular form payload, API request/response, and database row shapes.
 *
 * Screens:  Entity Creation Journey  (/entities/create)
 *           Entity Dashboard         (/entity-dashboard)
 *           Reconciliation           (/reconciliation)
 *           Exception Queue          (/exception-queue)
 *           Transactions             (/transactions)
 *           Entity Audit Logs        (/entity-audit-logs)
 *           User Management          (/user-management)
 *
 * Backend tables:
 *   entities, entity_settings, entity_intake_channels,
 *   entity_matching_policies, entity_modules, entity_roles
 */

// ────────────────────────────────────────────────────────────
// Catalog / enum value types (keys must exist in catalog tables)
// ────────────────────────────────────────────────────────────

/** Code from industry_catalog.code */
export type IndustryCatalogCode = string;

/** Code from region_catalog.code */
export type RegionCatalogCode = string;

/** Key from source_catalog.source_key (e.g. 'sap', 'erp', 'manual', 'not_applicable') */
export type SourceKey = string;

/** module_catalog.module_key values supported by the platform */
export type ModuleKey =
  | 'models'
  | 'classification'
  | 'provider_governance'
  | 'api_integrations';

/** role_catalog.role_key values generated by the role engine */
export type RoleKey =
  | 'entity_admin'
  | 'finance_controller'
  | 'ap_manager'
  | 'ar_manager';

/** Supported intake channel identifiers */
export type IntakeChannelKey = 'sap' | 'upload' | 'vendor' | 'mail';

/** Matching validation method */
export type MatchingMethod = 'two_way' | 'three_way' | 'four_way';

/** E-Way bill requirement policy */
export type EwayBillPolicy =
  | 'not_applicable'
  | 'optional'
  | 'required'
  | 'required_above_threshold';

/** Entity lifecycle status (entities.status column) */
export type EntityStatus = 'draft' | 'active' | 'suspended' | 'archived';

/** Intake channel connection lifecycle */
export type ConnectionStatus =
  | 'not_configured'
  | 'pending'
  | 'connected'
  | 'error'
  | 'disabled';

// ────────────────────────────────────────────────────────────
// Step 1 — Entity Profile
// Form fields: clientId, clientName, industry, region, adminEmail, notes
// ────────────────────────────────────────────────────────────

export interface EntityProfile {
  /** Unique entity identifier key — stored as entities.entity_key. e.g. "NORTHLINE-001" */
  entityId: string;
  /** Human-readable display name — stored as entities.name */
  entityName: string;
  /** Industry code from industry_catalog — stored as entities.industry_code */
  industry: IndustryCatalogCode;
  /** Region code from region_catalog — stored as entities.region_code */
  region: RegionCatalogCode;
  /** Primary admin email — stored as entity_settings.primary_admin_email */
  adminEmail: string;
  /** Optional onboarding notes — stored as entity_settings.onboarding_notes */
  notes?: string;
}

// ────────────────────────────────────────────────────────────
// Step 2 — Intake Channel Configuration
// Form: .intake-option checkboxes + per-mode config panels
// DB table: entity_intake_channels (one row per enabled channel)
// ────────────────────────────────────────────────────────────

/** SAP touchless integration — stored as entity_intake_channels.connection_settings */
export interface SapIntakeConfig {
  endpoint: string;    // SAP OData/REST endpoint URL
  clientId: string;    // SAP OAuth client ID — stored as client_id
  docTypes: string;    // Comma-separated document type keys (e.g. "invoices,po,grn")
}

/** Direct file upload channel */
export interface UploadIntakeConfig {
  maxFileSize: string;      // e.g. "10mb" — stored as max_file_size
  acceptedFormats: string;  // Comma-separated: "pdf,xml,jpg,png" — stored as accepted_formats[]
}

/** Vendor self-service portal */
export interface VendorIntakeConfig {
  portalUrl: string;    // External vendor portal URL — stored as portal_url
  autoApprove: boolean; // Auto-approve vendor submissions — stored as auto_approve
}

/** Mail/email connector */
export interface MailIntakeConfig {
  provider: 'gmail' | 'microsoft365' | 'imap';
  mailbox: string;
  username: string;
  password: string;         // Handled as a secret — NOT stored in connection_settings
  folder: string;           // e.g. "inbox"
  syncFrequency: 'every_5_minutes' | 'every_15_minutes' | 'hourly' | 'every_6_hours' | 'daily';
  connectionStatus: string; // UI-only display label
}

/** All intake channel configs, keyed by channel. Only defined keys are active. */
export interface IntakeConfig {
  sap?: SapIntakeConfig;
  upload?: UploadIntakeConfig;
  vendor?: VendorIntakeConfig;
  mail?: MailIntakeConfig;
}

// ────────────────────────────────────────────────────────────
// Step 3 — Matching Policy
// Form: matchingMode, poSource, grnSource, inspectionSource, ewayBillMode
// DB table: entity_matching_policies (one row per entity)
// ────────────────────────────────────────────────────────────

export interface MatchingPolicy {
  /** Validation method: 2-way (Invoice+PO), 3-way (+GRN), or 4-way (+Inspection) */
  matchingMode: MatchingMethod;
  /** Purchase order data source — stored as purchase_order_source_key */
  poSource: SourceKey;
  /** Goods receipt note source — stored as grn_source_key. Set to 'not_applicable' for two_way. */
  grnSource: SourceKey;
  /** Inspection/service-entry source — stored as inspection_source_key. Only used for four_way. */
  inspectionSource: SourceKey;
  /** E-Way bill requirement — stored as eway_bill_policy */
  ewayBillMode: EwayBillPolicy;
  /** Amount threshold in INR — stored as eway_bill_threshold. Only used when ewayBillMode = 'required_above_threshold'. */
  ewayBillThreshold: number;
}

// ────────────────────────────────────────────────────────────
// Step 4 — Project Scope (AP / AR toggles)
// Form: enableAP, enableAR checkboxes
// DB: entity_settings.accounts_payable_enabled, .accounts_receivable_enabled
// ────────────────────────────────────────────────────────────

export interface ProjectScope {
  /** Enables Accounts Payable module — stored as entity_settings.accounts_payable_enabled */
  accountsPayable: boolean;
  /** Enables Accounts Receivable module — stored as entity_settings.accounts_receivable_enabled */
  accountsReceivable: boolean;
}

// ────────────────────────────────────────────────────────────
// Step 5 — Access & Role Engine
// Form: enableUserCreation, enableRbac, defaultRole, adminUsername, adminPassword
// DB: entity_settings, entity_roles
// ────────────────────────────────────────────────────────────

export interface RoleDefinition {
  key: RoleKey;
  label: string;
  scope: string;        // e.g. "AP + AR"
  permissions: string;  // e.g. "Approve, reconcile, reporting"
}

export interface RoleEngine {
  enabled: boolean;
  defaultRole: RoleKey;
  roles: RoleDefinition[];
}

export interface AdminCredentials {
  username: string; // Stored as entity_settings.primary_admin_username
  password: string; // Min 8 chars — only used on create, never returned by API
}

export interface AccessConfig {
  /** Enable user creation for this entity — stored as entity_settings.user_creation_enabled */
  userCreation: boolean;
  /** Enable RBAC enforcement — stored as entity_settings.rbac_enabled */
  rbac: boolean;
  /** Default role key — stored as entity_settings.default_role_key */
  defaultRole: RoleKey;
  roleEngine: RoleEngine;
  adminCredentials: AdminCredentials;
}

// ────────────────────────────────────────────────────────────
// Step 6 — Module Toggles
// Form: mod-toggle checkboxes for each sub-feature
// DB: entity_modules (module_key + settings JSONB per row)
// ────────────────────────────────────────────────────────────

export interface ModuleConfig {
  /** Master toggle — entity_modules where module_key = 'models' */
  modelIntegration: boolean;
  /** Models sub-setting — stored in entity_modules.settings.prompt_versioning */
  promptVersioning: boolean;

  /** Master toggle — entity_modules where module_key = 'classification' */
  documentClassification: boolean;
  /** Classification sub-setting — stored in entity_modules.settings.class_override */
  classOverride: boolean;

  /** Master toggle — entity_modules where module_key = 'provider_governance' */
  providerGovernance: boolean;
  /** Provider governance sub-setting — stored in entity_modules.settings.fallback_routing */
  fallbackRouting: boolean;

  /** Master toggle — entity_modules where module_key = 'api_integrations' */
  apiIntegrations: boolean;
  /** API integrations sub-settings — stored in entity_modules.settings.* */
  gstTax: boolean;
  identityKyc: boolean;
  banking: boolean;
  businessCompliance: boolean;
}

// ────────────────────────────────────────────────────────────
// Full entity creation form payload
// Produced by buildPayload() in client-creation-journey.ts
// ────────────────────────────────────────────────────────────

export interface EntityCreatePayload {
  entity: EntityProfile;
  intakeModes: IntakeChannelKey[];
  intakeConfig: IntakeConfig;
  matchingPolicy: MatchingPolicy;
  projectScope: ProjectScope;
  access: AccessConfig;
  modules: ModuleConfig;
  status: 'draft' | 'created' | 'updated';
}

// ────────────────────────────────────────────────────────────
// API request body — POST /api/v1/tenants/:id/entities
// adminCredentials are stripped; adminUsername is promoted.
// ────────────────────────────────────────────────────────────

export interface EntityApiRequest {
  entity: EntityProfile;
  intakeModes: IntakeChannelKey[];
  intakeConfig: IntakeConfig;
  matchingPolicy: MatchingPolicy;
  projectScope: ProjectScope;
  access: Omit<AccessConfig, 'adminCredentials'> & {
    adminUsername: string; // Extracted from adminCredentials.username before send
  };
  modules: ModuleConfig;
  status: string;
  operation: 'create' | 'update';
}

// ────────────────────────────────────────────────────────────
// Database row shapes (typed API responses)
// ────────────────────────────────────────────────────────────

/** entities table row */
export interface EntityDbRow {
  id: string;                              // UUID PK
  tenant_id: string;
  entity_key: string;                      // e.g. "NORTHLINE-001"
  name: string;
  industry_code: IndustryCatalogCode | null;
  region_code: RegionCatalogCode | null;
  status: EntityStatus;
  created_by_user_id: string | null;
  created_at: string;                      // ISO timestamptz
  updated_at: string;
}

/** entity_settings table row */
export interface EntitySettingsDbRow {
  entity_id: string;
  tenant_id: string;
  primary_admin_email: string;
  primary_admin_username: string;
  primary_admin_user_id: string | null;
  onboarding_notes: string | null;
  user_creation_enabled: boolean;
  rbac_enabled: boolean;
  default_role_key: RoleKey;
  accounts_payable_enabled: boolean;
  accounts_receivable_enabled: boolean;
  created_at: string;
  updated_at: string;
}

/** entity_intake_channels table row */
export interface IntakeChannelDbRow {
  id: string;
  tenant_id: string;
  entity_id: string;
  channel_key: IntakeChannelKey;
  is_enabled: boolean;
  connection_settings: Record<string, unknown>; // JSONB — shape depends on channel_key
  secret_reference_id: string | null;
  connection_status: ConnectionStatus;
  last_connected_at: string | null;
  created_at: string;
  updated_at: string;
}

/** entity_matching_policies table row */
export interface MatchingPolicyDbRow {
  entity_id: string;
  tenant_id: string;
  matching_method: MatchingMethod;
  purchase_order_source_key: SourceKey;
  grn_source_key: SourceKey;
  inspection_source_key: SourceKey;
  eway_bill_policy: EwayBillPolicy;
  eway_bill_threshold: number;
  created_at: string;
  updated_at: string;
}

/** entity_modules table row */
export interface ModuleDbRow {
  tenant_id: string;
  entity_id: string;
  module_key: ModuleKey;
  is_enabled: boolean;
  settings: Record<string, unknown>; // JSONB — shape depends on module_key
  created_at: string;
  updated_at: string;
}

/** entity_roles table row (joined with roles) */
export interface EntityRoleDbRow {
  id: string;
  tenant_id: string;
  entity_id: string;
  role_id: string;
  role_key: RoleKey;
  label: string;
  scope_type: 'all' | 'ap' | 'ar' | 'ap_ar';
  is_enabled: boolean;
  is_default: boolean;
  source: 'engine' | 'custom';
  created_at: string;
  updated_at: string;
}

// ────────────────────────────────────────────────────────────
// Module settings JSONB shapes (entity_modules.settings)
// ────────────────────────────────────────────────────────────

export interface ModelsModuleSettings {
  prompt_versioning: boolean;
}

export interface ClassificationModuleSettings {
  class_override: boolean;
}

export interface ProviderGovernanceModuleSettings {
  fallback_routing: boolean;
}

export interface ApiIntegrationsModuleSettings {
  gst_tax: boolean;
  identity_kyc: boolean;
  banking: boolean;
  business_compliance: boolean;
}

// ────────────────────────────────────────────────────────────
// Intake channel connection_settings JSONB shapes
// (entity_intake_channels.connection_settings)
// ────────────────────────────────────────────────────────────

export interface SapConnectionSettings {
  endpoint: string;
  client_id: string;
  document_types: string[];
}

export interface UploadConnectionSettings {
  max_file_size: string;
  accepted_formats: string[];
}

export interface VendorConnectionSettings {
  portal_url: string;
  auto_approve: boolean;
}

export interface MailConnectionSettings {
  provider: 'gmail' | 'microsoft365' | 'imap';
  mailbox: string;
  username: string;
  folder: string;
  sync_frequency: string;
  connection_status: string; // UI display label, not the DB column
}

// ────────────────────────────────────────────────────────────
// Composite API responses
// ────────────────────────────────────────────────────────────

/** Response from GET /api/v1/tenants/:id/entities/:entityId/dashboard */
export interface EntityDashboardResponse {
  entity: EntityDbRow;
  settings: EntitySettingsDbRow;
  intakeChannels: IntakeChannelDbRow[];
  matchingPolicy: MatchingPolicyDbRow | null;
  modules: ModuleDbRow[];
  roles: EntityRoleDbRow[];
  assignments: Record<string, unknown>[];
  classifications: Record<string, unknown>[];
}

/** Single item in the entity list from GET /api/v1/tenants/:id/entities */
export interface EntityListItem {
  id: string;
  entity_key: string;
  name: string;
  industry_code: IndustryCatalogCode | null;
  region_code: RegionCatalogCode | null;
  status: EntityStatus;
  primary_admin_email?: string;
  default_role_key?: RoleKey;
  accounts_payable_enabled?: boolean;
  accounts_receivable_enabled?: boolean;
  rbac_enabled?: boolean;
  intake_modes?: IntakeChannelKey[];
  created_at: string;
}

// ────────────────────────────────────────────────────────────
// Validation constants (mirror backend validation rules)
// ────────────────────────────────────────────────────────────

export const ENTITY_VALIDATION = {
  entityId: {
    required: true,
    maxLength: 50,
    hint: 'Alphanumeric, hyphens and underscores only (e.g. NORTHLINE-001)'
  },
  entityName: {
    required: true,
    minLength: 2,
    maxLength: 200
  },
  adminEmail: {
    required: true,
    pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  },
  adminPassword: {
    requiredOnCreate: true,
    minLength: 8
  },
  ewayBillThreshold: {
    min: 0
  }
} as const;
